/**
 * @file lib/storage/db.ts
 * @description IndexedDB storage layer for the meet-transcript-saver Chrome extension.
 *
 * Uses the native browser IndexedDB API (no external library) to keep the
 * extension bundle small. All async operations are Promise-wrapped so callers
 * can use async/await throughout.
 *
 * Object stores
 * -------------
 *  meetings           - one row per Google Meet session
 *  transcript_entries - individual caption lines belonging to a meeting
 *  sync_queue         - batches of entries waiting to be uploaded to the server
 */

// =============================================================================
// Exported interfaces
// =============================================================================

/** A Google Meet session stored locally. */
export interface LocalMeeting {
  /** Unique meeting ID (UUID generated by the extension). */
  id: string;
  /** The authenticated user this meeting belongs to. */
  userId: string;
  /** Human-readable meeting title, if available. */
  title: string | null;
  /** The full Google Meet URL (e.g. https://meet.google.com/abc-defg-hij). */
  meetUrl: string;
  /** ISO-8601 timestamp when caption capture started. */
  startedAt: string;
  /** ISO-8601 timestamp when the meeting ended, or null if still ongoing. */
  endedAt: string | null;
  /** ISO-8601 timestamp when this record was first persisted locally. */
  createdAt: string;
}

/** A single caption line captured during a meeting. */
export interface LocalTranscriptEntry {
  /** Unique entry ID (UUID generated by the extension). */
  id: string;
  /** The meeting this entry belongs to. */
  meetingId: string;
  /** Monotonically increasing counter within the meeting (used for ordering). */
  sequence: number;
  /** Speaker display name, or null if unknown. */
  speaker: string | null;
  /** The raw caption text. */
  text: string;
  /** ISO-8601 timestamp when this caption segment started. */
  startedAt: string;
  /** Whether this entry has been successfully uploaded to the server. */
  synced: boolean;
}

/** A batch of transcript entries queued for upload. */
export interface SyncQueueItem {
  /** Auto-incremented primary key (undefined before first write). */
  id?: number;
  /** The meeting these entries belong to. */
  meetingId: string;
  /** The entries to upload in this batch. */
  entries: LocalTranscriptEntry[];
  /** Current upload status. */
  status: "pending" | "failed";
  /** Number of failed upload attempts so far. */
  retryCount: number;
  /** ISO-8601 timestamp when this batch was enqueued. */
  createdAt: string;
}

// =============================================================================
// Internal constants
// =============================================================================

const DB_NAME = "meet-transcript-saver";
const DB_VERSION = 1;

/** Object store names - kept as constants to avoid typo-driven bugs. */
const STORE = {
  MEETINGS: "meetings",
  TRANSCRIPT_ENTRIES: "transcript_entries",
  SYNC_QUEUE: "sync_queue",
} as const;

// =============================================================================
// Utility helpers
// =============================================================================

/**
 * Wraps an IDBRequest in a Promise so callers can use async/await.
 *
 * @template T  The type of `request.result`.
 * @param request  Any IDBRequest instance.
 * @returns A Promise that resolves with `request.result` or rejects with
 *          `request.error`.
 */
function idbRequest<T>(request: IDBRequest<T>): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

/**
 * Wraps an IDBTransaction in a Promise that resolves when the transaction
 * commits and rejects if it aborts.
 */
function idbTransaction(tx: IDBTransaction): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
    tx.onabort = () =>
      reject(tx.error ?? new DOMException("Transaction aborted"));
  });
}

// =============================================================================
// TranscriptDB class
// =============================================================================

/**
 * Provides all local-storage operations for the meet-transcript-saver
 * extension via a thin async wrapper around native IndexedDB.
 *
 * Usage:
 * ```ts
 * import { transcriptDB } from './lib/storage/db';
 * await transcriptDB.init();
 * await transcriptDB.saveMeeting({ ... });
 * ```
 */
export class TranscriptDB {
  /** The underlying IDB database handle; set after `init()` resolves. */
  private db: IDBDatabase | null = null;

  // ---------------------------------------------------------------------------
  // Initialisation
  // ---------------------------------------------------------------------------

  /**
   * Opens (and, on first run, creates) the IndexedDB database.
   * Must be called once before any other method.
   *
   * Idempotent - safe to call multiple times; subsequent calls are no-ops
   * if the DB is already open.
   */
  async init(): Promise<void> {
    if (this.db) return; // already initialised

    this.db = await new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open(DB_NAME, DB_VERSION);

      // Schema creation / migration
      request.onupgradeneeded = (event) => {
        const db = (event.target as IDBOpenDBRequest).result;

        // 1. meetings
        if (!db.objectStoreNames.contains(STORE.MEETINGS)) {
          const meetingsStore = db.createObjectStore(STORE.MEETINGS, {
            keyPath: "id",
          });
          // Allow fast look-ups of all meetings belonging to a user.
          meetingsStore.createIndex("user_id", "userId", { unique: false });
        }

        // 2. transcript_entries
        if (!db.objectStoreNames.contains(STORE.TRANSCRIPT_ENTRIES)) {
          const entriesStore = db.createObjectStore(STORE.TRANSCRIPT_ENTRIES, {
            keyPath: "id",
          });
          // Compound index used for ordering and uniqueness within a meeting.
          entriesStore.createIndex(
            "meeting_sequence",
            ["meetingId", "sequence"],
            { unique: true }
          );
          // Non-unique index for retrieving all entries for a given meeting.
          entriesStore.createIndex("meeting_id", "meetingId", {
            unique: false,
          });
        }

        // 3. sync_queue
        if (!db.objectStoreNames.contains(STORE.SYNC_QUEUE)) {
          // autoIncrement gives each queued batch a stable numeric PK.
          db.createObjectStore(STORE.SYNC_QUEUE, {
            keyPath: "id",
            autoIncrement: true,
          });
        }
      };

      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
      request.onblocked = () =>
        reject(
          new Error(
            "IndexedDB open blocked - close other tabs using this extension"
          )
        );
    });
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /**
   * Returns the open IDBDatabase, throwing if `init()` has not been called.
   */
  private getDB(): IDBDatabase {
    if (!this.db) {
      throw new Error("TranscriptDB is not initialised. Call init() first.");
    }
    return this.db;
  }

  // ---------------------------------------------------------------------------
  // meetings store
  // ---------------------------------------------------------------------------

  /**
   * Inserts or replaces a meeting record.
   * Uses `put` so calling this with an existing `id` performs an upsert.
   */
  async saveMeeting(meeting: LocalMeeting): Promise<void> {
    const db = this.getDB();
    const tx = db.transaction(STORE.MEETINGS, "readwrite");
    tx.objectStore(STORE.MEETINGS).put(meeting);
    await idbTransaction(tx);
  }

  /**
   * Retrieves a meeting by its primary key.
   * Returns `undefined` if no record with that ID exists.
   */
  async getMeeting(id: string): Promise<LocalMeeting | undefined> {
    const db = this.getDB();
    const tx = db.transaction(STORE.MEETINGS, "readonly");
    const store = tx.objectStore(STORE.MEETINGS);
    return idbRequest<LocalMeeting | undefined>(store.get(id));
  }

  /**
   * Applies a partial update to an existing meeting.
   * Reads the current record, merges the updates, then writes it back.
   * Throws if the meeting does not exist.
   */
  async updateMeeting(
    id: string,
    updates: Partial<LocalMeeting>
  ): Promise<void> {
    const db = this.getDB();
    const tx = db.transaction(STORE.MEETINGS, "readwrite");
    const store = tx.objectStore(STORE.MEETINGS);

    // Read the existing record inside the same transaction.
    const existing = await idbRequest<LocalMeeting | undefined>(store.get(id));
    if (!existing) {
      tx.abort();
      throw new Error(`Meeting not found: ${id}`);
    }

    // Ensure the primary key is never accidentally overwritten.
    store.put({ ...existing, ...updates, id });
    await idbTransaction(tx);
  }

  // ---------------------------------------------------------------------------
  // transcript_entries store
  // ---------------------------------------------------------------------------

  /**
   * Inserts or replaces a transcript entry.
   * Uses `put` so duplicate entries (same `id`) are safely overwritten.
   */
  async saveTranscriptEntry(entry: LocalTranscriptEntry): Promise<void> {
    const db = this.getDB();
    const tx = db.transaction(STORE.TRANSCRIPT_ENTRIES, "readwrite");
    tx.objectStore(STORE.TRANSCRIPT_ENTRIES).put(entry);
    await idbTransaction(tx);
  }

  /**
   * Returns all transcript entries for a given meeting that have not yet been
   * uploaded, ordered by sequence number (ascending).
   */
  async getUnsyncedEntries(
    meetingId: string
  ): Promise<LocalTranscriptEntry[]> {
    const db = this.getDB();
    const tx = db.transaction(STORE.TRANSCRIPT_ENTRIES, "readonly");
    const store = tx.objectStore(STORE.TRANSCRIPT_ENTRIES);
    const index = store.index("meeting_id");

    // Fetch all entries for this meeting, then filter client-side.
    // IDB cannot filter on two properties simultaneously without a compound
    // index that includes `synced`, so we keep the index lean and filter here.
    const allEntries = await idbRequest<LocalTranscriptEntry[]>(
      index.getAll(meetingId)
    );

    return allEntries
      .filter((e) => !e.synced)
      .sort((a, b) => a.sequence - b.sequence);
  }

  /**
   * Marks a set of transcript entries (identified by sequence number within a
   * meeting) as synced. Runs all updates inside a single transaction.
   */
  async markEntriesSynced(
    meetingId: string,
    sequences: number[]
  ): Promise<void> {
    if (sequences.length === 0) return;

    const db = this.getDB();
    const tx = db.transaction(STORE.TRANSCRIPT_ENTRIES, "readwrite");
    const store = tx.objectStore(STORE.TRANSCRIPT_ENTRIES);
    const index = store.index("meeting_sequence");
    const sequenceSet = new Set(sequences);

    // Build an IDBKeyRange for the compound index to limit the cursor scan.
    // Iterate from [meetingId, min_sequence] to [meetingId, max_sequence].
    const minSeq = Math.min(...sequences);
    const maxSeq = Math.max(...sequences);
    const range = IDBKeyRange.bound([meetingId, minSeq], [meetingId, maxSeq]);

    await new Promise<void>((resolve, reject) => {
      const cursorReq = index.openCursor(range);

      cursorReq.onsuccess = () => {
        const cursor = cursorReq.result;
        if (!cursor) {
          resolve();
          return;
        }

        const entry = cursor.value as LocalTranscriptEntry;
        if (sequenceSet.has(entry.sequence)) {
          cursor.update({ ...entry, synced: true });
        }
        cursor.continue();
      };

      cursorReq.onerror = () => reject(cursorReq.error);
    });

    await idbTransaction(tx);
  }

  // ---------------------------------------------------------------------------
  // sync_queue store
  // ---------------------------------------------------------------------------

  /**
   * Adds a new sync batch to the queue with status `"pending"`.
   */
  async enqueueSyncBatch(
    meetingId: string,
    entries: LocalTranscriptEntry[]
  ): Promise<void> {
    const item: SyncQueueItem = {
      meetingId,
      entries,
      status: "pending",
      retryCount: 0,
      createdAt: new Date().toISOString(),
    };

    const db = this.getDB();
    const tx = db.transaction(STORE.SYNC_QUEUE, "readwrite");
    tx.objectStore(STORE.SYNC_QUEUE).add(item);
    await idbTransaction(tx);
  }

  /**
   * Returns all sync queue items whose status is `"pending"`, ordered by
   * auto-incremented `id` (i.e. insertion order, oldest first).
   */
  async getPendingSyncBatches(): Promise<SyncQueueItem[]> {
    const db = this.getDB();
    const tx = db.transaction(STORE.SYNC_QUEUE, "readonly");
    const store = tx.objectStore(STORE.SYNC_QUEUE);

    const all = await idbRequest<SyncQueueItem[]>(store.getAll());
    return all.filter((item) => item.status === "pending");
  }

  /**
   * Updates the status (and optionally the retryCount) of a sync queue item.
   * Useful for marking a batch as `"failed"` after an upload error.
   */
  async updateSyncBatchStatus(
    id: number,
    status: "pending" | "failed",
    retryCount?: number
  ): Promise<void> {
    const db = this.getDB();
    const tx = db.transaction(STORE.SYNC_QUEUE, "readwrite");
    const store = tx.objectStore(STORE.SYNC_QUEUE);

    const existing = await idbRequest<SyncQueueItem | undefined>(store.get(id));
    if (!existing) {
      tx.abort();
      throw new Error(`Sync queue item not found: ${id}`);
    }

    store.put({
      ...existing,
      status,
      retryCount: retryCount ?? existing.retryCount,
    });
    await idbTransaction(tx);
  }

  /**
   * Removes a sync queue item by its auto-incremented ID.
   * Call this after a batch has been successfully uploaded.
   */
  async deleteSyncBatch(id: number): Promise<void> {
    const db = this.getDB();
    const tx = db.transaction(STORE.SYNC_QUEUE, "readwrite");
    tx.objectStore(STORE.SYNC_QUEUE).delete(id);
    await idbTransaction(tx);
  }
}

// =============================================================================
// Singleton export
// =============================================================================

/**
 * Shared singleton instance. Import this throughout the extension instead of
 * constructing a new TranscriptDB - the underlying IDBDatabase connection is
 * reused across all callers.
 *
 * Always call `await transcriptDB.init()` once during extension startup before
 * invoking any other method.
 */
export const transcriptDB = new TranscriptDB();
